name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DB_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DB_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.C5I_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.C5I_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e ".[local,test]"

      - name: Workflow deployment (assets only upload)
        run: |
          dbx deploy Data-preprocessing --assets-only
      
      - name: Workflow deployment (assets only upload)
        run: |
          dbx deploy Model-Training --assets-only
      
      - name: Workflow deployment (assets only upload)
        run: |
          dbx deploy Model-Inferencing --assets-only
      
      
      
      
      
      

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}.
          draft: false
          prerelease: false

